<?php
declare(strict_types=1);
namespace App\Entities;


class User
{
    // Primary key (AUTO_INCREMENT)
    private ?int $id = null;
    // UUID string (generated by DB default)
    private string $userId = '';
    private string $userName = '';
    private string $email = '';
    private string $password = '';
    private string $firstName = '';
    private string $lastName = '';
    private string $phoneNumber = '';
    private string $verificationCode = '';
    private string $alias = '';

    // BIT in MySQL -> bool in PHP
    private bool $isActive = true;
    private bool $isBlocked = false;
    private bool $isReported = false;
    private bool $isSpecial = false;
    private int $loginType = 1;
    private int $userType = 1;
    private int $status = 1;
    private int $suscriptionId = 0; // kept name as in DB
    // Nullable dates
    private ?\DateTimeInterface $birthday = null;
    private ?\DateTimeInterface $lastLogin = null;
    // Timestamps (created_at NOT NULL, updated_at NULL)
    private \DateTimeInterface $createdAt;
    private ?\DateTimeInterface $updatedAt = null;
    public function __construct()
    {
        // created_at must be set; default to "now" if not provided
        $this->createdAt = new \DateTimeImmutable('now');
    }
    // ID
    public function getId(): ?int
    {
        return $this->id;
    }
    public function setId(?int $id): self
    {
        $this->id = $id;
        return $this;
    }
    // user_id (UUID string)
    public function getUserId(): string
    {
        return $this->userId;
    }
    public function setUserId(string $userId): self
    {
        $this->userId = $userId;
        return $this;
    }
    // user_name
    public function getUserName(): string
    {
        return $this->userName;
    }
    public function setUserName(string $userName): self
    {
        $this->userName = $userName;
        return $this;
    }
    // email
    public function getEmail(): string
    {
        return $this->email;
    }
    public function setEmail(string $email): self
    {
        $this->email = $email;
        return $this;
    }
    // password
    public function getPassword(): string
    {
        return $this->password;
    }
    public function setPassword(string $password): self
    {
        $this->password = $password;
        return $this;
    }
    // first_name
    public function getFirstName(): string
    {
        return $this->firstName;
    }
    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;
        return $this;
    }
    // last_name
    public function getLastName(): string
    {
        return $this->lastName;
    }
    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;
        return $this;
    }
    // phone_number
    public function getPhoneNumber(): string
    {
        return $this->phoneNumber;
    }
    public function setPhoneNumber(string $phoneNumber): self
    {
        $this->phoneNumber = $phoneNumber;
        return $this;
    }
    // verification_code
    public function getVerificationCode(): string
    {
        return $this->verificationCode;
    }
    public function setVerificationCode(string $verificationCode): self
    {
        $this->verificationCode = $verificationCode;
        return $this;
    }

    public function getAlias(): string
    {
        return $this->alias;
    }

    public function setAlias(string $alias) : self
    {
        $this->alias = $alias;
        return $this;
    }

    // is_active
    public function isActive(): bool
    {
        return $this->isActive;
    }
    public function setIsActive(bool|int|string $isActive): self
    {
        // Accept common DB representations: 1/0, "1"/"0", "\x01"/"\x00"
        $this->isActive = $this->toBool($isActive);
        return $this;
    }
    // is_blocked
    public function isBlocked(): bool
    {
        return $this->isBlocked;
    }
    public function setIsBlocked(bool|int|string $isBlocked): self
    {
        $this->isBlocked = $this->toBool($isBlocked);
        return $this;
    }
    // is_reported
    public function isReported(): bool
    {
        return $this->isReported;
    }
    public function setIsReported(bool|int|string $isReported): self
    {
        $this->isReported = $this->toBool($isReported);
        return $this;
    }
    // is_special
    public function isSpecial(): bool
    {
        return $this->isSpecial;
    }
    public function setIsSpecial(bool|int|string $isSpecial): self
    {
        $this->isSpecial = $this->toBool($isSpecial);
        return $this;
    }
    // login_type
    public function getLoginType(): int
    {
        return $this->loginType;
    }
    public function setLoginType(int $loginType): self
    {
        $this->loginType = $loginType;
        return $this;
    }
    // user_type
    public function getUserType(): int
    {
        return $this->userType;
    }
    public function setUserType(int $userType): self
    {
        $this->userType = $userType;
        return $this;
    }
    // status
    public function getStatus(): int
    {
        return $this->status;
    }
    public function setStatus(int $status): self
    {
        $this->status = $status;
        return $this;
    }
    // suscription_id (note spelling kept as-is)
    public function getSuscriptionId(): int
    {
        return $this->suscriptionId;
    }
    public function setSuscriptionId(int $suscriptionId): self
    {
        $this->suscriptionId = $suscriptionId;
        return $this;
    }
    // birthday
    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }
    public function setBirthday(?\DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;
        return $this;
    }
    // last_login
    public function getLastLogin(): ?\DateTimeInterface
    {
        return $this->lastLogin;
    }
    public function setLastLogin(?\DateTimeInterface $lastLogin): self
    {
        $this->lastLogin = $lastLogin;
        return $this;
    }
    // created_at
    public function getCreatedAt(): \DateTimeInterface
    {
        return $this->createdAt;
    }
    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;
        return $this;
    }
    // updated_at
    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }
    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;
        return $this;
    }
    // Hydration helpers (optional)
    public static function fromArray(array $row): self
    {
        $u = new self();
        // Map and cast defensively; ignore unknown keys
        if (array_key_exists('id', $row)) $u->setId(self::toNullableInt($row['id']));
        if (array_key_exists('user_id', $row)) $u->setUserId((string)$row['user_id']);
        if (array_key_exists('user_name', $row)) $u->setUserName((string)$row['user_name']);
        if (array_key_exists('email', $row)) $u->setEmail((string)$row['email']);
        if (array_key_exists('password', $row)) $u->setPassword((string)$row['password']);
        if (array_key_exists('first_name', $row)) $u->setFirstName((string)$row['first_name']);
        if (array_key_exists('last_name', $row)) $u->setLastName((string)$row['last_name']);
        if (array_key_exists('phone_number', $row)) $u->setPhoneNumber((string)$row['phone_number']);
        if (array_key_exists('verification_code', $row)) $u->setVerificationCode((string)$row['verification_code']);
        if (array_key_exists('is_active', $row)) $u->setIsActive($row['is_active']);
        if (array_key_exists('is_blocked', $row)) $u->setIsBlocked($row['is_blocked']);
        if (array_key_exists('is_reported', $row)) $u->setIsReported($row['is_reported']);
        if (array_key_exists('is_special', $row)) $u->setIsSpecial($row['is_special']);
        if (array_key_exists('login_type', $row)) $u->setLoginType((int)$row['login_type']);
        if (array_key_exists('user_type', $row)) $u->setUserType((int)$row['user_type']);
        if (array_key_exists('status', $row)) $u->setStatus((int)$row['status']);
        if (array_key_exists('suscription_id', $row)) $u->setSuscriptionId((int)$row['suscription_id']);
        if (array_key_exists('birthday', $row)) {
            $u->setBirthday(self::toNullableDate($row['birthday']));
        }
        if (array_key_exists('last_login', $row)) {
            $u->setLastLogin(self::toNullableDateTime($row['last_login']));
        }
        if (array_key_exists('created_at', $row)) {
            $created = self::toDateTime($row['created_at']);
            if ($created !== null) {
                $u->setCreatedAt($created);
            }
        }
        if (array_key_exists('updated_at', $row)) {
            $u->setUpdatedAt(self::toNullableDateTime($row['updated_at']));
        }
        return $u;
    }
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'user_id' => $this->userId,
            'user_name' => $this->userName,
            'email' => $this->email,
            'password' => $this->password,
            'first_name' => $this->firstName,
            'last_name' => $this->lastName,
            'phone_number' => $this->phoneNumber,
            'verification_code' => $this->verificationCode,
            'is_active' => $this->isActive ? 1 : 0,
            'is_blocked' => $this->isBlocked ? 1 : 0,
            'is_reported' => $this->isReported ? 1 : 0,
            'is_special' => $this->isSpecial ? 1 : 0,
            'login_type' => $this->loginType,
            'user_type' => $this->userType,
            'status' => $this->status,
            'suscription_id' => $this->suscriptionId,
            'birthday' => $this->birthday?->format('Y-m-d'),
            'last_login' => $this->lastLogin?->format('Y-m-d H:i:s'),
            'created_at' => $this->createdAt->format('Y-m-d H:i:s'),
            'updated_at' => $this->updatedAt?->format('Y-m-d H:i:s'),
        ];
    }
    // Internal casting helpers
    private static function toNullableInt(mixed $v): ?int
    {
        if ($v === null || $v === '') return null;
        return (int)$v;
    }
    private static function toBool(mixed $v): bool
    {
        // Handle ints, strings from PDO for BIT(1) (can be "\x00"/"\x01"), and booleans
        if (is_bool($v)) return $v;
        if (is_int($v)) return $v === 1;
        if (is_string($v)) {
            // Normalize common representations
            if ($v === "\x00" || $v === "\0") return false;
            if ($v === "\x01") return true;
            $lv = strtolower(trim($v));
            if ($lv === '1' || $lv === 'true' || $lv === 't' || $lv === 'yes' || $lv === 'y') return true;
            if ($lv === '0' || $lv === 'false' || $lv === 'f' || $lv === 'no' || $lv === 'n' || $lv === '') return false;
        }
        return (bool)$v;
        }
    private static function toNullableDate(mixed $v): ?\DateTimeInterface
    {
        if ($v === null || $v === '') return null;
        // Accept DateTimeInterface or string
        if ($v instanceof \DateTimeInterface) return $v;
        try {
            // Expecting 'Y-m-d'
            return new \DateTimeImmutable((string)$v);
        } catch (\Exception) {
            return null;
        }
    }
    private static function toNullableDateTime(mixed $v): ?\DateTimeInterface
    {
        if ($v === null || $v === '') return null;
        if ($v instanceof \DateTimeInterface) return $v;
        try {
            // Expecting 'Y-m-d H:i:s'
            return new \DateTimeImmutable((string)$v);
        } catch (\Exception) {
            return null;
        }
    }
    private static function toDateTime(mixed $v): ?\DateTimeInterface
    {
        $dt = self::toNullableDateTime($v);
        return $dt;
    }
}